"""Dados padrão carregados automaticamente no primeiro start."""

TIPOS_PADRAO = [
    "CONSUMIVEIS EM GERAL", "LINHA DE TRANSMISSÃO", "TI/INFORMATICA", "SOLDA EM GERAL",
    "PINTURA EM GERAL", "VIAS DE ACESSO EM GERAL", "REFRIGERAÇÃO EM GERAL", "FERRAMENTAS EM GERAL",
    "CUPIM - ESP", "VEICULO EM GERAL", "COPA E COZINHA EM GERAL", "BATERIAS/PILHAS EM GERAL",
    "UTENSILIOS EM GERAL", "BELZONA - ESP", "RESISTENCIAS DE AQUECIMENTO EM GERAL",
    "CONECTORES DE SUBESTAÇÃO EM GERAL", "MUFLAS/BOTINHAS/TERMINACOES", "EMBALAGENS EM GERAL",
    "SIEMENS - ESP", "WEG - ESP", "ELOS - ESP", "DELTA STAR - ESP", "MEGABRAS - ESP",
    "NANOPROTECH - ESP", "SALVI BR - ESP", "SADEL - ESP", "TREETECH - ESP", "TILUB - ESP",
    "BOBINAS MADEIRA EM GERAL", "ELETRONICA EM GERAL", "MERCADO LIVRE - ESP", "ROLAMENTOS EM GERAL",
]
